# Generated by Django 3.1.5 on 2021-06-27 17:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chedBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
