# Generated by Django 3.1.5 on 2021-06-27 17:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chedBackend', '0002_auto_20210627_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaschedraui',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
